### ISSUE TITLE
Refactoring ToDo List

### ISSUE THREAD

**Issue by acbuynak** [osu-capstone-afrl/photogrammetry-capture-motion#4]
## Refactoring ToDo List

- [x] Create Ring Class inside of `shapes.py` 
* Takes in diameter and level, returns the xyz points that form a ring

- [x] Move Rotation Matrix Generator ([link](https://github.com/osu-capstone-afrl/photogrammetry-capture-motion/blob/9b45588f5db3ff4e370a0cef0d122a3f58728166/scripts/path_plans.py#L222-L264)) into `DetectedObject` parent class.
- [x] Create member function inside `DetectedObject` that input list of (xyz) tuples. 
* Similar to this section [(link)](https://github.com/osu-capstone-afrl/photogrammetry-capture-motion/blob/9b45588f5db3ff4e370a0cef0d122a3f58728166/scripts/path_plans.py#L208-L218)
* Uses rotMatrix generator to get rotation matrix.
* Use transformation tool to generate transform list, and subsequently poses
* Returns a list of poses

- [x] Update Documentation & TypeAssisting (similar to [link](https://github.com/osu-capstone-afrl/photogrammetry-capture-motion/blob/9b45588f5db3ff4e370a0cef0d122a3f58728166/scripts/path_plans.py#L54))

- [x] Create `_global_origin` as a  member of `DetectedObject`. Add usage throughout code.
* Specifically in Ring Class, rotMatrix generator, inclined planes method.

- [x] Rewrite `InclinedPlanes` to be transformation based. 
* Edit `scaling`:  Adjusts the angle in which planes are rotated towards the part
* Edit `offset`:  Setback along

- [x] Edit `SteppedRings`
* Add `offset`:  Distance variable along newly defined z-axis of the camera frame. (scalar dist)
* Add `scaling`:  Modifies the size of each ring diameter (multiplier)

After refactoring steps as defined above.... We'll start developing the `Dome` Method.

**Comment by acbuynak** [comment]
Update:

Created new branch `melodic-refactor`.
Completed below tasks..

- [x] Created `Rings` _function_ in `shapes.py`
- [x] Moved `_rotationMatrix_orient_z_axis` into `DetectedObject` class
- [x] Created new `DetectedObject` function: `_process_points_into_path`
